# Generated by Django 4.1 on 2023-10-02 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="personnel_number",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
